# Generated by Django 4.2.7 on 2025-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_visitor_remove_interaction_element_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, unique=True)),
                ('pulls', models.IntegerField(default=0)),
                ('reward', models.FloatField(default=0.0)),
            ],
        ),
    ]
