# Generated by Django 4.2.7 on 2026-02-27 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_airecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='E.g. click, hover, section_view, scroll_depth …', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Client-side event timestamp (ISO 8601 from JS Date).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('element', models.CharField(blank=True, default='', max_length=255)),
                ('is_cta', models.BooleanField(default=None, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in ms (hover, section_dwell, time_on_page).', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='tag, text, depth, seconds, read, form_id, field, referrer …')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='session',
            name='referrer',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Passed to the frontend and sent back with every event batch.', unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cookie_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stored in the visitor_id cookie on the client.', unique=True),
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='landing.session'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'event_type'], name='landing_eve_session_817996_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['section'], name='landing_eve_section_e022ed_idx'),
        ),
    ]
