# Generated by Django 4.2.7 on 2026-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_event_alter_session_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conversion',
            field=models.BooleanField(default=False, help_text='Placeholder for future conversion tracking.'),
        ),
        migrations.AddField(
            model_name='session',
            name='cta_clicked',
            field=models.BooleanField(default=False, help_text='True if the visitor clicked any CTA element.'),
        ),
        migrations.AddField(
            model_name='session',
            name='engaged_time_ms',
            field=models.IntegerField(default=0, help_text='Total active time on page in milliseconds.'),
        ),
        migrations.AddField(
            model_name='session',
            name='max_scroll_pct',
            field=models.IntegerField(default=0, help_text='Highest scroll-depth percentage reached during the session.'),
        ),
        migrations.AddField(
            model_name='session',
            name='price_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with the pricing section.'),
        ),
        migrations.AddField(
            model_name='session',
            name='primary_intent',
            field=models.CharField(default='unknown', help_text='Dominant intent bucket: "price", "service", "trust", or "unknown".', max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='quick_scan_score',
            field=models.FloatField(default=0.0, help_text='1.0 if user scrolled far but dwelt little; 0.0 otherwise.'),
        ),
        migrations.AddField(
            model_name='session',
            name='service_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with the services section.'),
        ),
        migrations.AddField(
            model_name='session',
            name='trust_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with testimonials + FAQ.'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['ended_at'], name='landing_ses_ended_a_4cf813_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_active'], name='landing_ses_is_acti_11705c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['primary_intent'], name='landing_ses_primary_69401f_idx'),
        ),
    ]
