# Generated by Django 4.2.7 on 2026-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_session_conversion_session_cta_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='contact_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with the contact section.'),
        ),
        migrations.AddField(
            model_name='session',
            name='location_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with the locations section.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='primary_intent',
            field=models.CharField(default='unknown', help_text='Dominant intent bucket: "price", "service", "trust", "location", "contact", or "unknown".', max_length=32),
        ),
        migrations.AlterField(
            model_name='session',
            name='trust_intent_score',
            field=models.FloatField(default=0.0, help_text='Weighted score reflecting engagement with testimonials, FAQ, trust bar, and about.'),
        ),
    ]
