# Generated by Django 4.2.7 on 2026-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_session_contact_intent_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='visit_number',
            field=models.IntegerField(default=1, help_text='Which visit this is for the visitor (1 = first, 2 = second, …).'),
        ),
    ]
