# Generated by Django 4.2.7 on 2026-03-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_session_visit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtxBanditArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.CharField(help_text='Machine-readable key, e.g. "pricing_highlight_plan_2".', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Optional human-readable label.', max_length=255)),
                ('page_config', models.JSONField(blank=True, default=dict, help_text='Config dict consumed by applyPageConfig on the frontend.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive arms are excluded from selection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['arm_id'],
            },
        ),
        migrations.CreateModel(
            name='BanditDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_bucket', models.CharField(db_index=True, help_text='E.g. "mobile_price", "desktop_unknown".', max_length=100)),
                ('context_json', models.JSONField(blank=True, default=dict, help_text='Full context snapshot used when making the decision.')),
                ('explore', models.BooleanField(help_text='True if this was an exploration pick (random).')),
                ('epsilon', models.FloatField(help_text='Epsilon value at decision time.')),
                ('reward', models.FloatField(blank=True, help_text='Filled in when the session ends (1.0 if CTA clicked, else 0.0).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='landing.ctxbanditarm')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_decision', to='landing.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_decisions', to='landing.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['context_bucket'], name='landing_ban_context_3f6fb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BanditArmStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_bucket', models.CharField(db_index=True, max_length=100)),
                ('n', models.IntegerField(default=0, help_text='Number of times this arm was pulled in this bucket.')),
                ('sum_reward', models.FloatField(default=0.0, help_text='Cumulative reward for this arm in this bucket.')),
                ('mean_reward', models.FloatField(default=0.0, help_text='sum_reward / n  (cached for fast lookup).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='landing.ctxbanditarm')),
            ],
            options={
                'indexes': [models.Index(fields=['context_bucket', 'arm'], name='landing_ban_context_5d8f54_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='banditarmstat',
            constraint=models.UniqueConstraint(fields=('context_bucket', 'arm'), name='unique_bucket_arm'),
        ),
    ]
