# Generated by Django 4.2.7 on 2026-03-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_remove_old_banditarm_rename_ctxbanditarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='banditdecision',
            name='context_vector',
            field=models.JSONField(blank=True, default=list, help_text='Numeric feature vector (list of floats) used by the linear bandit.'),
        ),
        migrations.AlterField(
            model_name='banditdecision',
            name='context_bucket',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Legacy bucket string (no longer used by the linear bandit).', max_length=100),
        ),
        migrations.AlterField(
            model_name='banditdecision',
            name='context_json',
            field=models.JSONField(blank=True, default=dict, help_text='Human-readable context snapshot used when making the decision.'),
        ),
        migrations.CreateModel(
            name='LinUCBParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_matrix', models.JSONField(help_text='d×d matrix (list of lists) for ridge regression.')),
                ('b_vector', models.JSONField(help_text='d-length vector for ridge regression.')),
                ('n', models.IntegerField(default=0, help_text='Total number of observations (pulls) for this arm.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linucb_param', to='landing.banditarm')),
            ],
            options={
                'verbose_name': 'LinUCB Parameter',
                'verbose_name_plural': 'LinUCB Parameters',
            },
        ),
    ]
