# Generated by Django 4.2.7 on 2026-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_banditdecision_context_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banditdecision',
            name='predicted_score',
            field=models.FloatField(blank=True, help_text="The model's predicted reward for the chosen arm at decision time.", null=True),
        ),
        migrations.AlterField(
            model_name='linucbparam',
            name='A_matrix',
            field=models.JSONField(help_text='8×8 grid tracking what visitors this arm has been shown to (feature combinations).'),
        ),
        migrations.AlterField(
            model_name='linucbparam',
            name='b_vector',
            field=models.JSONField(help_text='8-number list tracking which visitor features led to CTA clicks for this arm.'),
        ),
        migrations.AlterField(
            model_name='linucbparam',
            name='n',
            field=models.IntegerField(default=0, help_text='Total number of times this arm has been shown to a visitor.'),
        ),
    ]
