# Generated by Django 4.2.7 on 2026-03-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_add_predicted_score_to_banditdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='banditarm',
            name='affected_sections',
            field=models.JSONField(blank=True, default=list, help_text='Section IDs this arm modifies, e.g. ["pricing"]. Used for observation-gated reward.'),
        ),
        migrations.AddField(
            model_name='banditdecision',
            name='chosen_arm_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of arm_id strings in the chosen slate.'),
        ),
        migrations.AddField(
            model_name='banditdecision',
            name='merged_page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Merged page_config applied to the frontend for this slate.'),
        ),
        migrations.AddField(
            model_name='banditdecision',
            name='updated_arm_ids',
            field=models.JSONField(blank=True, default=list, help_text='Arm IDs that were actually updated with reward (observation-gated).'),
        ),
        migrations.AlterField(
            model_name='banditdecision',
            name='arm',
            field=models.ForeignKey(blank=True, help_text='Legacy single-arm FK (nullable for slate decisions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='landing.banditarm'),
        ),
    ]
