# Generated by Django 4.2.7 on 2026-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_slate_bandit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pricing_cta_clicked',
            field=models.BooleanField(default=False, help_text='True if the visitor clicked a CTA within the pricing section (plan purchase intent).'),
        ),
        migrations.AlterField(
            model_name='banditdecision',
            name='reward',
            field=models.FloatField(blank=True, help_text='Filled in when the session ends (1.0 if pricing-plan CTA clicked, 0.5 if any other CTA clicked, else 0.0).', null=True),
        ),
    ]
