# Generated by Django 4.2.7 on 2026-03-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_tiered_reward_pricing_cta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinUCBParam',
            new_name='LinearArmParam',
        ),
        migrations.AlterModelOptions(
            name='lineararmparam',
            options={
                'verbose_name': 'Linear Arm Parameter',
                'verbose_name_plural': 'Linear Arm Parameters',
            },
        ),
        migrations.AlterField(
            model_name='lineararmparam',
            name='arm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linear_param', to='landing.banditarm'),
        ),
    ]
